### PR TITLE
QoL improvements for frame data modals

### PR DESCRIPTION
**Pull request by xiaogz**
I really appreciate http://meleeframedata.com/!

When I was looking through each character's frame data, I thought how nice it would be to use left/right to forward/backward the frames.

I figured I might as well give it a shoot (can't sleep).

Also, I saw how the out-of-bound frame path is handled and figured we can just wrap around.

### CODE REVIEW

**Comment by xiaogz** [comment]
Although I can't manage to figure out why the keypress events are not received unless you click on either forward or backward at least once....

If that's found out I can add the fix in.

**Comment by mitchhit234** [comment]
Thanks for the updates! I'll try and figure out why it won't take keypresses right away as well

**Comment by xiaogz** [comment]
@mitchhit234 Wow you merged fast! I planned on correcting that bug I pointed out after work in this PR. Basically if I create a map somewhere mapping string (move) to data index (int) then everything will be fine. Since you merged already I'll create a PR after work. I don't mind if you revert this merge since moves with more  frames than jab1 will be cutoff!

**Comment by mitchhit234** [comment]
Oh, I didn't notice that about the jab1 frames, yeah I'll have to fix that lol

**Comment by mitchhit234** [comment]
I may just have to revert it back to normal tomorrow. I'm getting weird errors when trying to do that mapping strategy involved with data being templated

**Comment by xiaogz** [comment]
Yeah np I understand. I looked more into it too and apparently sqlalchemy results need custom serialization before they can be used in javascript side. If you can revert just the frame wrap around commit and preserve the key navigation part that'll be appreciated!

**Pull request merged**
